spring:
  datasource:
    url: jdbc:tc:postgresql:15:///testdb
    username: testuser
    password: testpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
