server:
  port: 8080

logging:
  level:
    root: info

spring:
  application:
    name: mockbalance
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5444/mock_balance_test
    username: mock_balance_user
    password: mock_balance_root
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

batch:
  size: 2000


